export const dashboardStyles = {
  container: {
    display: "flex",
    minHeight: "100vh",
    background: "#f8fafc",
    color: "#0f172a",
    fontFamily: "system-ui, -apple-system, sans-serif",
  },
  sidebar: {
    width: "250px",
    background: "#ffffff",
    borderRight: "1px solid #e2e8f0",
    display: "flex",
    flexDirection: "column" as const,
    padding: "20px 0",
  },
  sidebarHeader: {
    padding: "0 20px 20px 20px",
    borderBottom: "1px solid #e2e8f0",
    display: "flex",
    flexDirection: "column" as const,
    gap: "2px",
  },
  sidebarBrand: {
    fontSize: "20px",
    fontWeight: "bold" as const,
    color: "#0f172a",
    margin: 0,
  },
  sidebarSub: {
    fontSize: "9px",
    letterSpacing: "1.5px",
    color: "#2563eb",
    fontWeight: "bold" as const,
    textTransform: "uppercase" as const,
  },
  nav: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    padding: "16px 12px",
    flex: 1,
  },
  navItem: (active: boolean) => ({
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px",
    borderRadius: "6px",
    border: "none",
    background: active ? "#e2e8f0" : "transparent",
    color: active ? "#1e40af" : "#475569",
    fontSize: "14px",
    fontWeight: active ? "600" : "500",
    cursor: "pointer",
    textAlign: "left" as const,
    outline: "none",
    textDecoration: "none",
  }),
  badge: {
    background: "#ef4444",
    color: "#ffffff",
    fontSize: "10px",
    fontWeight: "bold" as const,
    padding: "1px 6px",
    borderRadius: "10px",
  },
  logoutBtnContainer: {
    padding: "12px 16px",
    borderTop: "1px solid #e2e8f0",
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
  },
  logoutBtn: {
    width: "100%",
    padding: "10px",
    background: "#f1f5f9",
    border: "1px solid #cbd5e1",
    color: "#475569",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "500" as const,
    textAlign: "center" as const,
    transition: "background 0.2s",
  },
  main: {
    flex: 1,
    padding: "32px",
    overflowY: "auto" as const,
    background: "transparent",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    borderBottom: "1px solid #e2e8f0",
    paddingBottom: "16px",
  },
  panelTitle: {
    fontSize: "24px",
    fontWeight: "600" as const,
    margin: 0,
    color: "#0f172a",
  },
  card: {
    background: "#ffffff",
    border: "1px solid #e2e8f0",
    borderRadius: "8px",
    padding: "20px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "6px",
    marginBottom: "16px",
  },
  formLabel: {
    fontSize: "12px",
    fontWeight: "600" as const,
    color: "#475569",
  },
  formInput: {
    background: "#ffffff",
    border: "1px solid #cbd5e1",
    borderRadius: "6px",
    padding: "10px 12px",
    color: "#0f172a",
    fontSize: "14px",
    outline: "none",
    width: "100%",
  },
  formSelect: {
    background: "#ffffff",
    border: "1px solid #cbd5e1",
    borderRadius: "6px",
    padding: "10px 12px",
    color: "#0f172a",
    fontSize: "14px",
    outline: "none",
    width: "100%",
    cursor: "pointer",
  },
  formSubmit: {
    padding: "10px 20px",
    background: "#2563eb",
    color: "#ffffff",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600" as const,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    transition: "background 0.2s",
  },
  btnDanger: {
    padding: "6px 12px",
    background: "#fef2f2",
    border: "1px solid #fca5a5",
    color: "#b91c1c",
    borderRadius: "4px",
    fontSize: "12px",
    cursor: "pointer",
  },
  btnSecondary: {
    padding: "6px 12px",
    background: "#ffffff",
    border: "1px solid #cbd5e1",
    color: "#475569",
    borderRadius: "4px",
    fontSize: "12px",
    cursor: "pointer",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: "14px",
    marginTop: "12px",
  },
  th: {
    padding: "12px 16px",
    fontSize: "12px",
    fontWeight: "600" as const,
    color: "#475569",
    borderBottom: "2px solid #e2e8f0",
    textAlign: "left" as const,
  },
  tr: {
    borderBottom: "1px solid #e2e8f0",
    background: "transparent",
  },
  td: {
    padding: "12px 16px",
    color: "#334155",
  },
  badgeRead: (isRead: boolean) => ({
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: "12px",
    fontSize: "11px",
    fontWeight: "600" as const,
    background: isRead ? "#d1fae5" : "#dbeafe",
    color: isRead ? "#065f46" : "#1e40af",
    border: "1px solid " + (isRead ? "#a7f3d0" : "#bfdbfe"),
  }),
};
