export const dashboardStyles = {
  container: {
    display: "flex",
    minHeight: "100vh",
    background: "#09090b",
    color: "#fafafa",
    fontFamily: "system-ui, -apple-system, sans-serif",
  },
  sidebar: {
    width: "250px",
    background: "#18181b",
    borderRight: "1px solid #27272a",
    display: "flex",
    flexDirection: "column" as const,
    padding: "20px 0",
  },
  sidebarHeader: {
    padding: "0 20px 20px 20px",
    borderBottom: "1px solid #27272a",
    display: "flex",
    flexDirection: "column" as const,
    gap: "2px",
  },
  sidebarBrand: {
    fontSize: "20px",
    fontWeight: "bold" as const,
    color: "#ffffff",
    margin: 0,
  },
  sidebarSub: {
    fontSize: "9px",
    letterSpacing: "1.5px",
    color: "#38bdf8",
    fontWeight: "bold" as const,
    textTransform: "uppercase" as const,
  },
  nav: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
    padding: "16px 12px",
    flex: 1,
  },
  navItem: (active: boolean) => ({
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px",
    borderRadius: "6px",
    border: "none",
    background: active ? "#27272a" : "transparent",
    color: active ? "#38bdf8" : "#a1a1aa",
    fontSize: "14px",
    fontWeight: active ? "600" : "500",
    cursor: "pointer",
    textAlign: "left" as const,
    outline: "none",
    textDecoration: "none",
  }),
  badge: {
    background: "#ef4444",
    color: "#ffffff",
    fontSize: "10px",
    fontWeight: "bold" as const,
    padding: "1px 6px",
    borderRadius: "10px",
  },
  logoutBtnContainer: {
    padding: "12px 16px",
    borderTop: "1px solid #27272a",
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
  },
  logoutBtn: {
    width: "100%",
    padding: "10px",
    background: "#27272a",
    border: "1px solid #3f3f46",
    color: "#e4e4e7",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "500" as const,
    textAlign: "center" as const,
    transition: "background 0.2s",
  },
  main: {
    flex: 1,
    padding: "32px",
    overflowY: "auto" as const,
    background: "transparent",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "24px",
    borderBottom: "1px solid #27272a",
    paddingBottom: "16px",
  },
  panelTitle: {
    fontSize: "24px",
    fontWeight: "600" as const,
    margin: 0,
    color: "#ffffff",
  },
  card: {
    background: "#18181b",
    border: "1px solid #27272a",
    borderRadius: "8px",
    padding: "20px",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "6px",
    marginBottom: "16px",
  },
  formLabel: {
    fontSize: "12px",
    fontWeight: "600" as const,
    color: "#a1a1aa",
  },
  formInput: {
    background: "#09090b",
    border: "1px solid #27272a",
    borderRadius: "6px",
    padding: "10px 12px",
    color: "#ffffff",
    fontSize: "14px",
    outline: "none",
    width: "100%",
  },
  formSelect: {
    background: "#09090b",
    border: "1px solid #27272a",
    borderRadius: "6px",
    padding: "10px 12px",
    color: "#ffffff",
    fontSize: "14px",
    outline: "none",
    width: "100%",
    cursor: "pointer",
  },
  formSubmit: {
    padding: "10px 20px",
    background: "#2563eb",
    color: "#ffffff",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600" as const,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    transition: "background 0.2s",
  },
  btnDanger: {
    padding: "6px 12px",
    background: "#7f1d1d",
    border: "1px solid #b91c1c",
    color: "#fecaca",
    borderRadius: "4px",
    fontSize: "12px",
    cursor: "pointer",
  },
  btnSecondary: {
    padding: "6px 12px",
    background: "#27272a",
    border: "1px solid #3f3f46",
    color: "#e4e4e7",
    borderRadius: "4px",
    fontSize: "12px",
    cursor: "pointer",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: "14px",
    marginTop: "12px",
  },
  th: {
    padding: "12px 16px",
    fontSize: "12px",
    fontWeight: "600" as const,
    color: "#a1a1aa",
    borderBottom: "2px solid #27272a",
    textAlign: "left" as const,
  },
  tr: {
    borderBottom: "1px solid #27272a",
    background: "transparent",
  },
  td: {
    padding: "12px 16px",
    color: "#e4e4e7",
  },
  badgeRead: (isRead: boolean) => ({
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: "12px",
    fontSize: "11px",
    fontWeight: "600" as const,
    background: isRead ? "#064e3b" : "#1e3a8a",
    color: isRead ? "#34d399" : "#93c5fd",
    border: "1px solid " + (isRead ? "#065f46" : "#1e40af"),
  }),
};
