export const dashboardStyles = {
  container: {
    display: "flex",
    minHeight: "100vh",
    background: "radial-gradient(ellipse at top, #0f172a 0%, #030306 100%)",
    color: "#f8fafc",
    fontFamily: "var(--font-sans)",
    overflow: "hidden",
  },
  sidebar: {
    width: "280px",
    background: "rgba(8, 8, 16, 0.75)",
    backdropFilter: "blur(20px)",
    borderRight: "1px solid rgba(255, 255, 255, 0.05)",
    display: "flex",
    flexDirection: "column" as const,
    padding: "24px 0",
    boxShadow: "10px 0 30px rgba(0, 0, 0, 0.5)",
    zIndex: 10,
  },
  sidebarHeader: {
    padding: "0 24px 24px 24px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.05)",
    display: "flex",
    flexDirection: "column" as const,
    gap: "4px",
  },
  sidebarBrand: {
    fontFamily: "var(--font-display)",
    fontSize: "26px",
    letterSpacing: "2px",
    color: "#ffffff",
    textTransform: "uppercase" as const,
    margin: 0,
    background: "linear-gradient(to right, #ffffff, #60a5fa)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  sidebarSub: {
    fontSize: "10px",
    letterSpacing: "3px",
    color: "#3b82f6",
    textTransform: "uppercase" as const,
    fontWeight: "bold",
  },
  nav: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "6px",
    padding: "24px 16px",
    flex: 1,
  },
  navItem: (active: boolean) => ({
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "14px 18px",
    borderRadius: "8px",
    border: "none",
    background: active ? "rgba(59, 130, 246, 0.15)" : "transparent",
    color: active ? "#60a5fa" : "#94a3b8",
    fontSize: "14px",
    fontWeight: active ? "600" : "500",
    cursor: "pointer",
    textAlign: "left" as const,
    transition: "all 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
    outline: "none",
    boxShadow: active ? "inset 0 1px 0 rgba(255,255,255,0.1), 0 4px 12px rgba(59,130,246,0.1)" : "none",
    borderLeft: active ? "3px solid #3b82f6" : "3px solid transparent",
  }),
  badge: {
    background: "#ef4444",
    color: "#ffffff",
    fontSize: "10px",
    fontWeight: "bold",
    padding: "2px 8px",
    borderRadius: "20px",
    boxShadow: "0 0 10px rgba(239, 68, 68, 0.4)",
  },
  logoutBtnContainer: {
    padding: "16px",
    borderTop: "1px solid rgba(255, 255, 255, 0.05)",
  },
  logoutBtn: {
    width: "100%",
    padding: "12px",
    background: "rgba(239, 68, 68, 0.05)",
    border: "1px solid rgba(239, 68, 68, 0.2)",
    color: "#f87171",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "600",
    letterSpacing: "1px",
    transition: "all 0.3s",
    textTransform: "uppercase" as const,
  },
  main: {
    flex: 1,
    padding: "48px",
    overflowY: "auto" as const,
    background: "transparent",
  },
  panelHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "40px",
  },
  panelTitle: {
    fontFamily: "var(--font-display)",
    fontSize: "42px",
    letterSpacing: "1px",
    margin: 0,
    fontWeight: "normal" as const,
    textTransform: "uppercase" as const,
  },
  card: {
    background: "rgba(20, 20, 32, 0.6)",
    backdropFilter: "blur(12px)",
    border: "1px solid rgba(255, 255, 255, 0.05)",
    borderRadius: "12px",
    padding: "32px",
    boxShadow: "0 20px 40px rgba(0, 0, 0, 0.3)",
    transition: "all 0.4s var(--ease-out)",
  },
  formGroup: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "8px",
    marginBottom: "20px",
  },
  formLabel: {
    fontSize: "12px",
    fontWeight: "600",
    textTransform: "uppercase" as const,
    letterSpacing: "1px",
    color: "#94a3b8",
  },
  formInput: {
    background: "rgba(13, 13, 24, 0.8)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: "6px",
    padding: "14px 18px",
    color: "#f8fafc",
    fontSize: "14px",
    outline: "none",
    transition: "all 0.3s",
    width: "100%",
  },
  formSelect: {
    background: "rgba(13, 13, 24, 0.8)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    borderRadius: "6px",
    padding: "14px 18px",
    color: "#f8fafc",
    fontSize: "14px",
    outline: "none",
    transition: "all 0.3s",
    width: "100%",
    cursor: "pointer",
  },
  formSubmit: {
    padding: "14px 28px",
    background: "linear-gradient(135deg, #3b82f6 0%, #1d4ed8 100%)",
    color: "#ffffff",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    letterSpacing: "0.5px",
    transition: "all 0.3s",
    boxShadow: "0 4px 15px rgba(59, 130, 246, 0.3)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  btnDanger: {
    padding: "6px 12px",
    background: "rgba(239, 68, 68, 0.1)",
    border: "1px solid rgba(239, 68, 68, 0.2)",
    color: "#f87171",
    borderRadius: "4px",
    fontSize: "12px",
    cursor: "pointer",
    transition: "all 0.3s",
  },
  btnSecondary: {
    padding: "6px 12px",
    background: "rgba(255, 255, 255, 0.03)",
    border: "1px solid rgba(255, 255, 255, 0.08)",
    color: "#94a3b8",
    borderRadius: "4px",
    fontSize: "12px",
    cursor: "pointer",
    transition: "all 0.3s",
  },
  table: {
    width: "100%",
    borderCollapse: "separate" as const,
    borderSpacing: "0 8px",
    textAlign: "left" as const,
    fontSize: "14px",
  },
  th: {
    padding: "16px 20px",
    fontSize: "11px",
    fontWeight: "700",
    textTransform: "uppercase" as const,
    letterSpacing: "1px",
    color: "#64748b",
    borderBottom: "1px solid rgba(255,255,255,0.05)",
  },
  tr: {
    background: "rgba(20, 20, 32, 0.4)",
    borderRadius: "8px",
    transition: "all 0.3s",
  },
  td: {
    padding: "18px 20px",
    borderBottom: "1px solid rgba(255, 255, 255, 0.02)",
  },
  badgeRead: (isRead: boolean) => ({
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: "20px",
    fontSize: "11px",
    fontWeight: "600",
    background: isRead ? "rgba(16, 185, 129, 0.1)" : "rgba(59, 130, 246, 0.1)",
    color: isRead ? "#34d399" : "#60a5fa",
    border: isRead ? "1px solid rgba(16, 185, 129, 0.2)" : "1px solid rgba(59, 130, 246, 0.2)",
  }),
};
